DOMAIN_IDS: list[int] = [1, 3, 4, 7, 9, 11, 32, 46, 99, 202]

SCIENTIFIC_NAMES = ['Carabus goryi',
 'Pterostichus coracinus',
 'Chlaenius aestivus',
 'Pasimachus elongatus',
 'Amara carinata',
 'Pasimachus sublaevis',
 'Chlaenius emarginatus',
 'Dicaelus furvus furvus',
 'Dicheirus piceus',
 'Pterostichus ordinarius',
 'Pterostichus novus',
 'Pterostichus melanarius melanarius',
 'Carabus serratus',
 'Brachinus alternans',
 'Harpalus protractus',
 'Cyclotrachelus furtivus',
 'Poecilus chalcites',
 'Pasimachus punctulatus',
 'Scarites subterraneus',
 'Pterostichus pensylvanicus',
 'Harpalus desertus',
 'Harpalus paratus',
 'Pterostichus acutipes acutipes',
 'Galerita bicolor',
 'Amara confusa',
 'Cyclotrachelus fucatus',
 'Cyclotrachelus torvus',
 'Synuchus impunctatus',
 'Scaphinotus oreophilus',
 'Harpalus pensylvanicus',
 'Cyclotrachelus sigillatus',
 'Discoderus parallelus',
 'Cyclotrachelus sodalis sodalis',
 'Sphaeroderus stenostomus lecontei',
 'Cyclotrachelus sodalis colossus',
 'Harpalus opacipennis',
 'Cymindis planipennis',
 'Pterostichus trinarius',
 'Anisodactylus similis',
 'Piosoma setosum',
 'Omus californicus',
 'Anisodactylus dulcicollis',
 'Cratacanthus dubius',
 'Anisodactylus carbonarius',
 'Scarites vicinus',
 'Calosoma calidum',
 'Sphaeroderus canadensis canadensis',
 'Cicindela punctulata',
 'Dicaelus dilatatus sinuatus',
 'Harpalus somnulentus',
 'Pterostichus rostratus',
 'Dicaelus furvus',
 'Cyclotrachelus convivus',
 'Dicaelus sculptilis',
 'Pterostichus panticulatus',
 'Dicaelus sculptilis sculptilis',
 'Calosoma affine',
 'Anisodactylus ovularis',
 'Galerita atripes',
 'Dicaelus dilatatus',
 'Dicaelus furvus carinatus',
 'Agonum placidum',
 'Cymindis neglecta',
 'Cyclotrachelus sodalis',
 'Amara conflata',
 'Cylindera unipunctata',
 'Pterostichus atratus',
 'Chlaenius tomentosus',
 'Metrius contractus',
 'Harpalus amputatus',
 'Agonum retractum',
 'Pterostichus permundus',
 'Cyclotrachelus faber',
 'Harpalus vagans',
 'Poecilus scitulus',
 'Anisodactylus haplomus',
 'Tetracha virginica',
 'Poecilus lucublandus',
 'Amara californica',
 'Amara obesa',
 'Pterostichus mutus',
 'Brachinus fumans',
 'Harpalus reversus',
 'Pasimachus subsulcatus',
 'Sphaeroderus stenostomus stenostomus',
 'Harpalus ellipsis',
 'Amara scitula',
 'Pterostichus tristis',
 'Harpalus amputatus amputatus',
 'Myas coracinus',
 'Chlaenius sericeus',
 'Cyclotrachelus freitagi',
 'Chlaenius platyderus',
 'Pterostichus stygicus',
 'Agonum gratiosum',
 'Dicaelus dilatatus dilatatus',
 'Dicaelus teter',
 'Anisodactylus merula',
 'Cicindela punctulata punctulata',
 'Dicaelus purpuratus splendidus',
 'Pterostichus acutipes',
 'Platynus decentis',
 'Pterostichus lama',
 'Amara littoralis',
 'Anisodactylus opaculus',
 'Dicaelus politus',
 'Agonum limbatum',
 'Calosoma frigidum',
 'Chlaenius erythropus',
 'Amara quenseli',
 'Agonum punctiforme',
 'Harpalus herbivagus',
 'Amara impuncticollis',
 'Pterostichus serripes',
 'Pterostichus caudicalis',
 'Scarites ocalensis',
 'Dicaelus purpuratus purpuratus',
 'Cyclotrachelus constrictus',
 'Pterostichus moestus',
 'Cyclotrachelus hypherpiformis',
 'Carabidae sp.',
 'Calathus opaculus',
 'Harpalus ventralis',
 'Cymindis cribricollis',
 'Dicaelus elongatus',
 'Amara coelebs',
 'Cyclotrachelus seximpressus',
 'Harpalus indigens',
 'Pterostichus (Hypherpes) sp.',
 'Amara tenax',
 'Harpalus providens',
 'Amara aenea',
 'Harpalus spadiceus',
 'Pterostichus adoxus',
 'Chlaenius tricolor tricolor',
 'Pasimachus californicus',
 'Harpalus caliginosus',
 'Brachinus cyanochroaticus',
 'Carabus sylvosus',
 'Anisodactylus furvus',
 'Sphaeroderus stenostomus',
 'Dicaelus purpuratus',
 'Calosoma scrutator',
 'Cyclotrachelus deceptus',
 'Anisodactylus rusticus',
 'Myas cyanescens',
 'Agonum cupreum',
 'Chlaenius tricolor',
 'Scaphinotus andrewsii',
 'Amara convexa',
 'Semiardistomis puncticollis']